### ISSUE TITLE
Gameserver Connection Lost After Loading

### ISSUE THREAD

**Issue by vicfelipe** [loggeru/AikaEmu#7]
- When occurs: After all features has loaded.

All steps was done perfectly, but happens this issue when GameServer has loaded.

I'm using windows 10 Pro x64

![1](https://user-images.githubusercontent.com/12769395/77281438-c2b0ed00-6ca5-11ea-84fc-4c6f1240d752.jpg)

Can you help me?
Thanks.

**Comment by lemestwo** [comment]
did you add the gameserver into the auth db?

> INSERT INTO `aikaemu_auth`.`game_servers`(`id`, `name`, `ip`, `port`) VALUES (1, 'AikaEmu', '127.0.0.1', 8822);

**Comment by vicfelipe** [comment]
I didn't, solved.

Sorry, my bad.
