### ISSUE TITLE
Client can not choose Nation

### ISSUE THREAD

**Issue by dks50217** [loggeru/AikaEmu#9]
SQL Nation table with Test1, Test2, Test3  but Nation list still empty

**Comment by dks50217** [comment]
solved , sorry AIKATW not support , I change to AIKABR and its work

**Comment by carlos026** [comment]
hello, I'm having problems accessing the nations, there is an error 'incorrect password' after choosing the world. I did all the steps perfectly. My discord is: OneHeap#4741

**Comment by dks50217** [comment]
make sure you are using aika brazil or mysql data is correct
